### ISSUE TITLE
Any android library artifactory publishing examples using 'com.android.tools.build:gradle:1.0.0'?

### ISSUE THREAD

**Issue by phlogistic** [dcendents/android-maven-plugin#10]

**Comment by dcendents** [comment]
It is done the same way as the standard maven plugin:

```gradle
uploadArchives {
	repositories {
		mavenDeployer {
			repository(url: 'file://e:/dev/m2/test')
		}
	}
}
```

Read the manual on the maven plugin for more options: https://gradle.org/docs/current/userguide/maven_plugin.html#uploading_to_maven_repositories
