### ISSUE TITLE
Publish to Artifactory with self-signed SSL certificate

### ISSUE THREAD

**Issue by blues-man** [dcendents/android-maven-plugin#12]
Hello,
I wonder if possible to publish to Artifactory with a self-signed ssl certificate, using maven option:

-Dmaven.wagon.http.ssl.insecure=true

because I got "peer not authenticated" if I try to publish any artifact, it didn't happened without SSL:

Could not HEAD 'https://IP:PORT/artifactory/repo/org/jfrog/buildinfo/build-info-extractor-gradle/3.0.1/build-info-extractor-gradle-3.0.1.pom'.

Bye

**Comment by dcendents** [comment]
I'm afraid I don't know.

It seems the gradle maven plugin uses the same maven wagon: http://gradle.org/docs/current/userguide/maven_plugin.html#wagonLibs

But other than that I don't I never had to use a self-signed ssl certificate, with gradle or even maven.
