### ISSUE TITLE
Exclude a class from aar

### ISSUE THREAD

**Issue by mgohin** [dcendents/android-maven-plugin#13]
Hi,

I want to exclude a class from the generated files, let's say Hello.java that I use for dev purposes, so I need 2 types of build : dev build with Hello.java and a release build without Hello.java.

How can I do it ? I'm pretty new to gradle and not finding something working.
 
EDIT

based on #3 I tried, but didn't worked

    android.libraryVariants.all { variant ->
        def name = variant.buildType.name
        if (name.equals(BuilderConstants.DEBUG)) {
            return; // Skip debug builds.
        }
        def task = project.tasks.create "removeDevFiles${name.capitalize()}", Jar
        task.dependsOn variant.javaCompile
        task.from variant.javaCompile.destinationDir
        task.exclude('**/Hello.class')
    }

**Comment by dcendents** [comment]
This is normally done through variants a combination of build types and flavor, see the manual for the android plugin here: http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants

From what you stated you seem to only need the default debug and release build types.

put your debug only files in src/debug/java (instead of src/main/java)

**Comment by mgohin** [comment]
If I use ```./gradlew clean installDebug``` it installs my aar lib on the device, it doesn't use your plugin to publish it to my local repo :(

**Comment by dcendents** [comment]
No, the installDebug is a task provided by the android plugin to install the debug apk on your device as explained here: http://tools.android.com/tech-docs/new-build-system/user-guide

The android-maven-plugin adds a task named install to install the aar artifacts into your local m2 repo as described by the maven plugin here: http://gradle.org/docs/current/userguide/maven_plugin.html
