### ISSUE TITLE
Generate maven exclusions

### ISSUE THREAD

**Issue by jitpack-io** [dcendents/android-maven-plugin#14]
Fantastic plugin, btw! 
Gradle supports excluding some transitive dependencies but these exclusions don't appear to be reflected in the generated pom. Seems like they should.

**Comment by dcendents** [comment]
The maven plugin (and my android-maven plugin) will not add exclusions based only on the module name (artifactId), it also requires the group (groupId) to be explicitely set, even if gradle does not care about it.

e.g.:

```gradle
    compile ('com.google.guava:guava:11.0.2') {
		exclude group: 'com.google.code.findbugs', module: 'jsr305'
	}
```

will correctly generate 

```maven
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>11.0.2</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>jsr305</artifactId>
          <groupId>com.google.code.findbugs</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by jitpack-io** [comment]
Makes perfect sense, thanks a lot!
