### ISSUE TITLE
Error: java.lang.IllegalArgumentException: android.compileSdkVersion is missing!

### ISSUE THREAD

**Issue by venkateshshukla** [dcendents/android-maven-plugin#16]
Applying this plugin causes the above error.

**Comment by dcendents** [comment]
Do you have a sample project or can you post the content of your gradle script?

**Comment by venkateshshukla** [comment]
This is the gradle script for the project. Removing line 2 removes all the errors.

http://pastebin.com/6eUCpELn

**Comment by dcendents** [comment]
which version of gradle and which version of the android-maven-plugin are you using?

**Comment by dcendents** [comment]
It looks like you are not using the correct version of the plugin, see the README.md on the main page to know which versions are compatible.

Using your build script, I could reproduce the error by using gradle 2.3 with the android-maven-plugin version 1.1. But if I use version 1.2 as required, then it all works fine.

**Comment by venkateshshukla** [comment]
Gradle 2.2.1

**Comment by dcendents** [comment]
Then you should be using the android-maven-plugin version 1.2, can you confirm it works with that version?

**Comment by venkateshshukla** [comment]
Excellent. It works with proper versioning.
The main error was the usage of 'android-maven' in place of 'com.github.dcendents.android-maven'.
