### ISSUE TITLE
Error build not generating pom file

### ISSUE THREAD

**Issue by doneill** [dcendents/android-maven-plugin#17]
I have used this plugin successfully in one of my aar projects to publish to an internal artifactory repository.  I am trying to apply the same logic to another build project but am getting the following error on ```artifactoryPublish```:  

```
A problem was found with the configuration of task ':artifactoryPublish'.
> File '/Users/dev/output/api/build/poms/pom-default.xml' specified for property 'mavenDescriptor' does not exist.
```

Here is my android-maven-plugin usage: 

```groovy
    dependencies {
        classpath 'com.github.dcendents:android-maven-plugin:1.2'
    }

apply plugin: 'com.android.library'
apply plugin: 'artifactory'
apply plugin: 'android-maven'

//defined in settings file
group = GROUP 
version = VERSION_NAME
```

**Comment by doneill** [comment]
I am past the pom generation issue, it seems it was related to lib-module naming in the project.  I was renaming the output aar in the build script but the pom generation expected the project name to be correct.

**Comment by dcendents** [comment]
Sorry I couldn't help you in time, thanks for letting us know what the problem was.

**Comment by badoualy** [comment]
How did you fix this finally? Because I have the same issue, the weird part is that someone else can publish the library on another computer with the same configuration... any clue?

version, group, url, password etc are specified in the same file

```java
apply plugin: 'com.jfrog.artifactory-upload'
apply plugin: 'com.github.dcendents.android-maven'

configurations {
    published
}

task sourceJar(type: Jar) {
    from "${android.sourceSets.main.java}"
    classifier "sources"
}

artifactoryPublish {
    dependsOn sourceJar
}

artifacts {
    published sourceJar
}

configure(install.repositories.mavenInstaller) {
    pom.project {
        licenses {
            license {
                name 'The Apache Software License, Version 2.0'
                url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                distribution 'repo'
            }
        }
    }
}

artifactory {
    contextUrl = artifactoryURL
    publish {
        repository {
            repoKey = artifactoryRepository
            username = artifactoryUser
            password = artifactoryPassword
        }
        defaults {
            publishConfigs('archives', 'published')
            publishArtifacts = true
            publishPom = true
            publishIvy = false
        }
    }
    resolve {
        repository {
            repoKey = artifactoryRepository
            username = artifactoryUser
            password = artifactoryPassword

        }
    }
}
```

**Comment by dcendents** [comment]
Just an idea, but are you using gradle wrapper or at least the same gradle version? Because if it does not work for you but works for someone else, I'd look at the version of gradle you are using.

Obviously, using the gradle wrapper will make sure you are both using the exact same version.

**Comment by badoualy** [comment]
Yes, we were using the same gradle version, but I managed to publish in console, the issue is just when using AndroidStudio to execute the task
