### ISSUE TITLE
javadoc generate erroe

### ISSUE THREAD

**Issue by jiaokang** [dcendents/android-maven-plugin#18]
Hi ,thx a lots for sharing this. i am in Chinese, so my computer use GBK encoding to generate javadoc and it has error , becasue Chinese String. So ,should I add any paramters in 'task javadoc'? And how ?

**Comment by dcendents** [comment]
Hi,

I'm not sure this relates to my plugin, it has probably more to do with the android plugin.

Can the following help you?

http://stackoverflow.com/questions/17033878/generate-javadocs-with-android-gradle-plugin
